apiVersion: apps/v1 # versão api que iremos utilizar
kind: Deployment # obj que vamos criar
metadata: #metadados do obj
  name: postgre
spec: # especificações do obj
  selector:
    matchLabels: # selector label pod
      app: postgre
  template: #especificação do pod
    metadata:
      labels: # label pod
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort : 5432
          env:
            - name: POSTGRES_PASSWORD
              value: Pg1234
            - name: POSTGRES_USER
              value: ecommerce
            - name: POSTGRES_DB
              value: ecommerce

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgre  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: fabricioveronez/fake-shop-desafio:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgre
            - name: DB_USER
              value: ecommerce
            - name: DB_PASSWORD
              value: Pg1234
            - name: DB_NAME
              value: ecommerce
            - name: FLASK_APP
              value: index.py

---

apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      nodePort: 30000
  selector:
    app: fakeshop